name: Docs

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "**.py"
      - "**.rst"
      - "poetry.lock"
      - "pyproject.toml"
  pull_request:
    paths:
      - ".github/workflows/check-docs.yml"
      - "**.py"
      - "**.rst"
      - "poetry.lock"
      - "pyproject.toml"

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docs:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up latest python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --with dev
      - name: Build doc
        run: poetry run sphinx-build -b html docs _build -EW --keep-going
      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_build"
  deploy:
    needs: docs
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
