name: Format

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/format.yml"
      - "**.py"
      - ".editorconfig"
  pull_request:
    paths:
      - ".github/workflows/format.yml"
      - "**.py"
      - ".editorconfig"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up latest python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --with dev
      - name: Check formatting
        run: poetry run black berserk tests check-endpoints.py --check